### ISSUE TITLE
may i use oidc.namebase.io directly with my site .

### ISSUE THREAD

**Issue by v1xingyue** [namebasehq/handshake-id-manager#3]
on news.namebase.io there is a login with handshake button just redirect to oidc.namebase.io , then jump to namebase.io set txt record , at last jump back to news.namebase.io . 
How can i implement one login identity like this.

**Comment by jeefave** [comment]
The protocol itself and some implementation details are described here: https://docs.namebase.io/handshake-login/handshake-based-oidc-authentication-protocol

You have different solutions available based on what you are trying to achieve:
- set up your own oidc provider wiring up the protocol
- use a 3rd party oidc provider wiring up the protocol (auth0, Okta)
- connect to an existing handshake oidc provider like namernews with some limitations
- using the open source code of the oidc server when it will be available (no date yet)

Let me know if I can answer specific questions!

**Comment by v1xingyue** [comment]
Thank you . I just implement this .
